# This template generates an Azure Pipeline Runner image and deploys it to an Azure Virtual Machine Scale Set

parameters:
  - name: azure_service_connection_name
    type: string

  - name: agent_pool
    type: object
    default:
      name: ubuntu-latest

  - name: vmss_name
    type: string

  - name: vmss_sku
    type: string
    default: Standard_D2s_v3
  
  - name: vmss_subnetid
    type: string
    default: /subscriptions/$(azure_subscription)/resourceGroups/$(build_agent_vnet_resource_group)/providers/Microsoft.Network/virtualNetworks/$(build_agent_vnet_name)/subnets/$(build_agent_subnet_name)

  - name: image_type
    type: string

  - name: image_template_name
    type: string

  - name: image_readme_name
    type: string

  - name: diskSizeGb
    type: number
    default: 0

  - name: storageType
    type: string
    default: StandardSSD_LRS

  - name: variable_group_name
    type: string
    default: 'Image Generation Variables'

  - name: repository_ref
    type: string
    default: 'self'

stages:
- stage: generate_image
  displayName: generate ${{ parameters.image_type }} image
  pool: ${{ parameters.agent_pool }}
  jobs:
  - template: image-generation.yml
    parameters:
      job_id: generate_image
      azureSubscription: ${{ parameters.azure_service_connection_name }}
      image_type: ${{ parameters.image_type }}
      image_template_name: ${{ parameters.image_template_name }}
      image_readme_name: ${{ parameters.image_readme_name }}
      agent_pool: ${{ parameters.agent_pool }}
      variable_group_name: ${{ parameters.variable_group_name }}
      create_release: false
      repository_ref: ${{ parameters.repository_ref }}
      keyvault_name: $(keyvault_name)
      keyvault_secret_name: $(keyvault_packer_secret_name)

- stage: deploy_vmss
  displayName: deploy ${{ parameters.image_type }} vmss
  jobs:
  - template: deploy-vmss.yml
    parameters:
      azure_service_connection_name: ${{ parameters.azure_service_connection_name }}
      agent_pool: ${{ parameters.agent_pool }}
      vmss_name: ${{ parameters.vmss_name }}
      vmss_sku: ${{ parameters.vmss_sku }}
      vmss_subnetid: ${{ parameters.vmss_subnetid }}
      image_ref: /subscriptions/$(azure_subscription)/resourceGroups/$(azure_resource_group)/providers/Microsoft.Compute/images/${{ parameters.image_type }}-$(Build.BuildId)
      image_type: ${{ parameters.image_type }}
      diskSizeGb: ${{ parameters.diskSizeGb }}
      storageType: ${{ parameters.storageType }}
      variable_group_name: ${{ parameters.variable_group_name }}
      repository_ref: ${{ parameters.repository_ref }}
