# This template uses an existing image to create or update an Azure Virtual Machine Scale Set

parameters:
  - name: azure_service_connection_name
    type: string

  - name: agent_pool
    type: object
    default:
      name: ubuntu-latest

  - name: vmss_name
    type: string

  - name: image_ref
    type: string

  - name: image_type
    type: string

  - name: variable_group_name
    type: string
    default: 'Image Generation Variables'

  - name: repository_ref
    type: string
    default: 'self'

jobs:
- job: 
  pool: ${{ parameters.agent_pool }}
  variables:
  - group: ${{ parameters.variable_group_name }}

  steps:
  - checkout: ${{ parameters.repository_ref }}
    fetchDepth: 0
    fetchTags: false

  - task: AzureCLI@2
    displayName: update vmss
    inputs:
      azureSubscription: ${{ parameters.azure_service_connection_name }}
      scriptType: 'pscore'
      failOnStandardError: true
      scriptLocation: scriptPath
      scriptPath: ./images.CI/linux-and-win/update-vmss.ps1
      arguments: >
        -VmssName ${{ parameters.vmss_name }}
        -ResourceGroupName $(azure_resource_group)
        -Image ${{ parameters.image_ref }}
        -ImageType ${{ parameters.image_type }}
